[2024-01-05T21:03:01.248+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:03:01.250+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable'
[2024-01-05T21:03:01.291+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:03:01.292+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable'
[2024-01-05T21:03:01.339+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:02:00+00:00 [queued]>
[2024-01-05T21:03:01.351+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:02:00+00:00 [queued]>
[2024-01-05T21:03:01.352+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T21:03:01.371+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-05 21:02:00+00:00
[2024-01-05T21:03:01.376+0000] {standard_task_runner.py:60} INFO - Started process 2291 to run task
[2024-01-05T21:03:01.380+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-05T21:02:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmpw4dkvn2q']
[2024-01-05T21:03:01.383+0000] {standard_task_runner.py:88} INFO - Job 93: Subtask PostgresTable
[2024-01-05T21:03:01.442+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:03:01.443+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:02:00+00:00/task_id=PostgresTable'
[2024-01-05T21:03:01.445+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:02:00+00:00 [running]> on host e91b89fa10db
[2024-01-05T21:03:01.547+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T21:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T21:02:00+00:00'
[2024-01-05T21:03:01.548+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-05T21:03:01.558+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:03:01.568+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:03:01.572+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-05T21:03:01.583+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240105T210200, start_date=20240105T210301, end_date=20240105T210301
[2024-01-05T21:03:01.633+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T21:03:01.658+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
