[2024-01-05T21:16:01.211+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:16:01.212+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable'
[2024-01-05T21:16:01.245+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:16:01.246+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable'
[2024-01-05T21:16:01.300+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:15:00+00:00 [queued]>
[2024-01-05T21:16:01.319+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:15:00+00:00 [queued]>
[2024-01-05T21:16:01.320+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T21:16:01.335+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-05 21:15:00+00:00
[2024-01-05T21:16:01.339+0000] {standard_task_runner.py:60} INFO - Started process 2891 to run task
[2024-01-05T21:16:01.345+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-05T21:15:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmp146y340t']
[2024-01-05T21:16:01.349+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask PostgresTable
[2024-01-05T21:16:01.414+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:16:01.414+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:15:00+00:00/task_id=PostgresTable'
[2024-01-05T21:16:01.416+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:15:00+00:00 [running]> on host e91b89fa10db
[2024-01-05T21:16:01.524+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T21:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T21:15:00+00:00'
[2024-01-05T21:16:01.525+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-05T21:16:01.535+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:16:01.547+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:16:01.551+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-05T21:16:01.562+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240105T211500, start_date=20240105T211601, end_date=20240105T211601
[2024-01-05T21:16:01.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T21:16:01.622+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
