[2024-01-05T21:14:00.807+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:14:00.808+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable'
[2024-01-05T21:14:00.844+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:14:00.845+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable'
[2024-01-05T21:14:00.894+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:13:00+00:00 [queued]>
[2024-01-05T21:14:00.904+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:13:00+00:00 [queued]>
[2024-01-05T21:14:00.905+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T21:14:00.920+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-05 21:13:00+00:00
[2024-01-05T21:14:00.925+0000] {standard_task_runner.py:60} INFO - Started process 2799 to run task
[2024-01-05T21:14:00.929+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-05T21:13:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmpt7zcabnh']
[2024-01-05T21:14:00.932+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask PostgresTable
[2024-01-05T21:14:01.015+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T21:14:01.016+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T21:13:00+00:00/task_id=PostgresTable'
[2024-01-05T21:14:01.018+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T21:13:00+00:00 [running]> on host e91b89fa10db
[2024-01-05T21:14:01.123+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T21:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T21:13:00+00:00'
[2024-01-05T21:14:01.124+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-05T21:14:01.136+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:14:01.147+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T21:14:01.152+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-05T21:14:01.165+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240105T211300, start_date=20240105T211400, end_date=20240105T211401
[2024-01-05T21:14:01.223+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T21:14:01.249+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
