[2024-01-06T12:44:01.235+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T12:44:01.236+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable'
[2024-01-06T12:44:01.272+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T12:44:01.272+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable'
[2024-01-06T12:44:01.327+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T12:43:00+00:00 [queued]>
[2024-01-06T12:44:01.339+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T12:43:00+00:00 [queued]>
[2024-01-06T12:44:01.339+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-06T12:44:01.360+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-06 12:43:00+00:00
[2024-01-06T12:44:01.365+0000] {standard_task_runner.py:60} INFO - Started process 507 to run task
[2024-01-06T12:44:01.368+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-06T12:43:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmpy5jfvvg0']
[2024-01-06T12:44:01.372+0000] {standard_task_runner.py:88} INFO - Job 226: Subtask PostgresTable
[2024-01-06T12:44:01.427+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T12:44:01.427+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T12:43:00+00:00/task_id=PostgresTable'
[2024-01-06T12:44:01.429+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T12:43:00+00:00 [running]> on host ca5b1c72379e
[2024-01-06T12:44:01.535+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T12:43:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T12:43:00+00:00'
[2024-01-06T12:44:01.536+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-06T12:44:01.546+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T12:44:01.556+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T12:44:01.562+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-06T12:44:01.573+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240106T124300, start_date=20240106T124401, end_date=20240106T124401
[2024-01-06T12:44:01.621+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-06T12:44:01.650+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
