[2024-01-06T14:15:00.981+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T14:15:00.982+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable'
[2024-01-06T14:15:01.017+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T14:15:01.017+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable'
[2024-01-06T14:15:01.064+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T14:14:00+00:00 [queued]>
[2024-01-06T14:15:01.075+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T14:14:00+00:00 [queued]>
[2024-01-06T14:15:01.076+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-06T14:15:01.096+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-06 14:14:00+00:00
[2024-01-06T14:15:01.101+0000] {standard_task_runner.py:60} INFO - Started process 2008 to run task
[2024-01-06T14:15:01.105+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-06T14:14:00+00:00', '--job-id', '322', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmp0zjjvd9m']
[2024-01-06T14:15:01.109+0000] {standard_task_runner.py:88} INFO - Job 322: Subtask PostgresTable
[2024-01-06T14:15:01.168+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509
[2024-01-06T14:15:01.169+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-06T14:14:00+00:00/task_id=PostgresTable'
[2024-01-06T14:15:01.170+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-06T14:14:00+00:00 [running]> on host ca5b1c72379e
[2024-01-06T14:15:01.277+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T14:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T14:14:00+00:00'
[2024-01-06T14:15:01.278+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-06T14:15:01.288+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T14:15:01.300+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T14:15:01.304+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-06T14:15:01.316+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240106T141400, start_date=20240106T141501, end_date=20240106T141501
[2024-01-06T14:15:01.361+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-06T14:15:01.389+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
